on:
  push:
    branches:
      - action/stable
    tags:
      - v*

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: kiwi operator test example
    steps:
    - uses: actions/checkout@v2
    - id: test
      uses:  operator-framework/community-operators@v1
      with:
        test-type: 'kiwi'
        stream: 'upstream-community-operators'
        name: 'aqua'
        version: '5.3.0'
        # pr-labels: 'allow/operator-version-overwrite bug'
