name: Operator action
on:
  push:
    # branches:
    #   - action/stable
    tags:
      - v*

jobs:
  kiwi-test-example:
    runs-on: ubuntu-latest
    name: kiwi operator test example
    steps:
    - id: Test
      uses:  operator-framework/community-operators@v1
      with:
        test-type: 'kiwi'
        stream: 'upstream-community-operators'
        name: 'aqua'
        version: '5.3.0'
        # pr-labels: 'allow/operator-version-overwrite bug'
  lemon-test-example:
    runs-on: ubuntu-latest
    name: lemon operator test example
    steps:
    - id: Test
      uses:  operator-framework/community-operators@v1
      with:
        test-type: 'lemon'
        stream: 'upstream-community-operators'
        name: 'aqua'
        version: '5.3.0'
        # pr-labels: 'allow/operator-version-overwrite bug'
  orange-test-example:
    runs-on: ubuntu-latest
    name: orange operator test example
    steps:
    - id: Test
      uses:  operator-framework/community-operators@v1
      with:
        test-type: 'orange'
        stream: 'upstream-community-operators'
        name: 'aqua'
        version: '5.3.0'
        pr-labels: 'allow/operator-version-overwrite bug'